name: 'Build Eclipse_for_S_Link'
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.2
        required: true
jobs:
  build-eclipse:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare 
        run: |
          pwd
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Package
        run: |          
          make USE_MIRROR=no V=${{ github.event.inputs.version }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Eclipse_for_S_Link
          path: |
            output/Eclipse_for_S_Link*.zip
          if-no-files-found: error
